[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"
authors = ["Antoine Montes"]

[dependencies]
crossterm = "0.27.0"
phf = { version = "0.11.2", features = ["macros"] }
ratatui = "0.24.0"
time = "0.3.30"
log = "0.4.20"
glam = "0.24.2"
